# Generated by Django 3.2.4 on 2021-06-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('desc', models.TextField(verbose_name='')),
                ('date', models.DateField(auto_now_add=True, verbose_name='')),
            ],
        ),
    ]
