# Generated by Django 3.2.4 on 2021-06-18 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blogs', '0002_auto_20210618_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesupload',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filesupload',
            name='file',
            field=models.FileField(max_length=150, upload_to='media/store/pdfs', verbose_name=''),
        ),
    ]
