# Generated by Django 3.2.4 on 2021-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blogs', '0004_alter_filesupload_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('url', models.URLField(verbose_name='')),
            ],
        ),
    ]
