# Generated by Django 3.2.4 on 2021-06-20 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blogs', '0006_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=550, unique=True, verbose_name=''),
            preserve_default=False,
        ),
    ]
