# Generated by Django 3.2.4 on 2021-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blogs', '0007_blogpost_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('short_desc', models.CharField(max_length=550, verbose_name='')),
                ('url', models.URLField(verbose_name='')),
            ],
        ),
    ]
