# Generated by Django 3.2.4 on 2021-06-21 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blogs', '0008_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/store/blog_imgs', verbose_name=''),
            preserve_default=False,
        ),
    ]
